# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78b17ac39495be272d93be67366f11ffe6bc0c8423b04189cc5dd736f3902aaff128252f013defd609d06d47e59e7d7fad22cf46b945c5a609715013c687de05

test:
  secret_key_base: fc3c9c3bb68572224865f3d21ac046792211f198dd493c3a7184d6bfca49aa0621b1bae1af248ce18954778638abb4d40760466faa1c809a7cf999961b5a38f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
